### ISSUE TITLE
[needs project info] Filter unified list based on attestor group

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#11]
In the list of projects provided by the unified API we should be able to apply a filter for a certain attestor group, this will filter the returned response to only show projects that have received at least 1 attestation from a given attestor group. 

We should be able to filter this list by on or multiple pre-defined attestor groups in the UI.

## Acceptance criteria
When we query for all projects using the [graphql API](https://backend.devouch.xyz/graphql), filtering to look only for projects that have received an attestation from a specific group we receive:

- [x] a list of only projects that have received at least 1 attestation from specified group
- [x] can include projects from multiple sources (giveth, gitcoin, optimism)
- [x] does not show projects that are not specified
- [x] can handle also being filtered by source platform simultaenously
- [x] the titles of the projects
- [x] the source platform
- [x] the short description of the project
- [x] count of flags AND vouches made my all attestor groups for each project listed in response
- [x] comment included in attestation
- [x] banner image

**Comment by divine-comedian** [comment]
@aminlatifi  - how should we specify an attestor group in our filter queries? 

Right now on the UI we look for them by schemaID and issuing authority address - should it be done by attestation UID?

**Comment by aminlatifi** [comment]
> Refere

No, it's not needed. We can return all valid attestor<->attestor group association in the UI

**Comment by aminlatifi** [comment]
It's a sample query filtering projects received attestation from a specific organisation ("Trace" here)

```graphql
query {
  projects (where: {
    attests_some:{
      attestorOrganisation: {
        organisation: {
          id_eq: "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722"
        }
      }
    }
  }) {
    source
    projectId
    attests {
      # vouch
      attestorOrganisation {
        # attestor {
        #   id
        # }
        organisation {
          id
          name
        }
      }
    }
  }
}
```

Result
```json
{
  "data": {
    "projects": [
      {
        "source": "giveth",
        "projectId": "2880",
        "attests": [
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0xf63f2a7159ee674aa6fce42196a8bb0605eafcf20c19e91a7eafba8d39fa0404",
                "name": "Giveth Verification Team"
              }
            }
          },
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          }
        ]
      },
      {
        "source": "giveth",
        "projectId": "123",
        "attests": [
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          },
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          },
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          }
        ]
      },
      {
        "source": "giveth",
        "projectId": "2881",
        "attests": [
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          },
          {
            "attestorOrganisation": {
              "organisation": {
                "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
                "name": "Trace"
              }
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by divine-comedian** [comment]
@aminlatifi I think to call this one done we'll need to have the project information included in the response.

**Comment by aminlatifi** [comment]
> @aminlatifi I think to call this one done we'll need to have the project information included in the response.

We have provisioned fields to contain information, they are just empty now and must be filled with a routine by #4 issue.
I think in this issue we can verify the correctness of API without those information be ready
@divine-comedian @maryjaf

**Comment by divine-comedian** [comment]
We'll need the project info to call this done.
