### ISSUE TITLE
CRITICAL P0 ISSUE: RF4 projects are not showing up on the app!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/DeVouch-BE#126]
<img width="1269" alt="Screenshot 2024-10-11 at 8 15 58 AM" src="https://github.com/user-attachments/assets/ab211dfe-82a4-4713-9719-530b0bfabfa0">

This is a huge issue as we role into RF6, please fix!!

**Comment by divine-comedian** [comment]
@MohammadPCh can you check this out please - it appears that the project data still exists on the source endpoint https://round4-api-eas.retrolist.app/projects

but for some reason none of these projects appear on the app or appear when querying the back-end for projects from rfRound 4

https://optimism.backend.devouch.xyz/graphql

**Comment by MohammadPCh** [comment]
Thanks to Kay, we fixed it! The issue was related to reading a variable from the vault on the DevOps side.

**Comment by LatifatAbdullahi** [comment]
Status: Test Passed

![image](https://github.com/user-attachments/assets/a08aed54-2791-41d5-87e5-8663813c33ff)


![image](https://github.com/user-attachments/assets/5cbd58a2-722c-471b-9092-c1223bd31f17)
