### ISSUE TITLE
Handling RF projects in multiple rounds

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#129]
Currently it is possible for RF projects to be involved in multiple rounds. It should be possible to query and find those projects when filtering for a specific RF round on the app. 

**Consider this:** 
> Current Round is 6
> Project A has been involved in RF rounds 4,5 & 6 
> Project B has been involved in RF rounds 4 & 6
> Project C  has been involved in RF rounds 5 & 6
> 
> User wants to filter to find all projects that were in RF 4. Project A & B should show up on filtered query. Project C should not

What we need to handle: 
- project data has array of rounds it has been involved in
- project description, title and banner image use the most recent round project data
- front-end handles showing multiple rounds on "source platform" badge 
- filtering works properly for projects that have been in multiple rounds

![Image](https://github.com/user-attachments/assets/8892ebd7-44fb-41ef-9fcc-a828bf860ac2)

**Comment by MohammadPCh** [comment]
The backend is ready. The frontend is yours, @mateodaza. Let me know if you need any help!
cc: @divine-comedian

**Comment by divine-comedian** [comment]
@mateodaza did you get a chance to look at this?

**Comment by mateodaza** [comment]
> @mateodaza did you get a chance to look at this?

nope, I'll make a issue on the front end
