### ISSUE TITLE
Retrieve attestation info if address has previously attested to project

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#15]
We should be able to know if a given address has attested for a project before, including the following information related to any relevant attestations. The difference between this one and #10 is this is meant for the single project page

- attester group they attested as
- if vouch or flag
- comments included in attestation

https://backend.devouch.xyz/graphql

## AC 
Should see results that shows: 

- [ ] name/title of attester group the given address has attested as (could be with multiple attester organizations)
- [ ] If each relevant attestation is a vouch or flag (true/false)
- [ ] comments included in each relevant attestation (if any)
- [ ] date of attestation

**Comment by aminlatifi** [comment]
@divine-comedian Do you mean we have to retrieve the user's attestation made before the user becomes eligible by the organization? 
I assumed eligible user's attestation only are counted if they are made after an organisation approved them as an eligible attestor.

**Comment by aminlatifi** [comment]
@divine-comedian If we want to count in the user's attestation made before being eligible, we will have hardship since we process/index chain events sequentially.

**Comment by divine-comedian** [comment]
No, we just want to know if the user has already attested to a given project, we will need to know this to show if they have an existing attestation they wish to revoke or to change their response (issue new attestation) for a given project.. 

Does this make sense?

**Comment by aminlatifi** [comment]
@divine-comedian This sample query
```graphql
query {
  projectAttestations(where:{
    project:{
      source_eq:"giveth",
      projectId_eq:"666"
    }
    attestorOrganisation: {
      attestor:{
        id_eq:"0xf23ea0b5f14afcbe532a1df273f7b233ebe41c78"
      }
    }
  }) {
    project {
      id
      source
      projectId
    }
    attestorOrganisation {
      attestor {
        id
      }
      organisation {
        id
        name
      }
    
    }
  }
}
```
With this response: 
```json
{
  "data": {
    "projectAttestations": [
      {
        "project": {
          "id": "giveth-666",
          "source": "giveth",
          "projectId": "666"
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0xf23ea0b5f14afcbe532a1df273f7b233ebe41c78"
          },
          "organisation": {
            "id": "0x2e22df9a11e06c306ed8f64ca45ceae02efcf8a443371395a78371bc4fb6f722",
            "name": "Trace"
          }
        }
      }
    ]
  }
}
```

**Comment by maryjaf** [comment]
could you please take a look ? @aminlatifi 
I think I should see this[ Project Id: 2880](https://sepolia.easscan.org/attestation/view/0x08fb6cbbec10a15f9fb973c251e12c122380128eb5ec9b0bb51f299610c7c729) in the response of below query, am I right? 

query {
  projectAttestations(where:{
    attestorOrganisation: {
      attestor:{
        id_eq:"0xcd192b61a8dd586a97592555c1f5709e032f2505" 
      }
    }
  }) {
    project {
      id
      source
      projectId
    }
    attestorOrganisation {
      attestor {
        id
        
      }
      organisation {
        id
        name
      }
    
    }
  }
  
}

![image](https://github.com/Giveth/DeVouch-BE/assets/111529185/d9cd71ac-183c-48ed-9575-5cd7e4fb8c43)

**Comment by aminlatifi** [comment]
> could you please take a look ? @aminlatifi I think I should see this[ Project Id: 2880](https://sepolia.easscan.org/attestation/view/0x08fb6cbbec10a15f9fb973c251e12c122380128eb5ec9b0bb51f299610c7c729) in the response of below query, am I right?
> 
> ```
> query {
> projectAttestations(where:{
> attestorOrganisation: {
>   attestor:{
>     id_eq:"0xcd192b61a8dd586a97592555c1f5709e032f2505" 
>   }
> }
>  }) {
>   project {
>    id
>    source
>    projectId
>  }
>  attestorOrganisation {
>    attestor {
>      id
>     
>    }
>    organisation {
>      id
>      name
>    }
> 
>  }
> }
> 
>  }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/330020525-d9cd71ac-183c-48ed-9575-5cd7e4fb8c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzMyOTcsIm5iZiI6MTcxNTY3Mjk5NywicGF0aCI6Ii8xMTE1MjkxODUvMzMwMDIwNTI1LWQ5Y2Q3MWFjLTE4M2MtNDhlZC05NTc1LTVjZDdlNGZiOGM0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwNzQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDlhZjczNjMyYzdjNWY1MzNlZWNiYjI2YzJkM2Y5MTNjOWFjNjM2M2E4N2E1ZDQwOGJkNDg3NjAwODI2NDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THVEyM7ACAGDaohbi49B0G0r7H5Z3_aCIUF3OeYIHBY)

The referenced attestation id is not filled in your attestation
<img width="511" alt="image" src="https://github.com/Giveth/DeVouch-BE/assets/5684607/d8770591-4fbc-4a04-bf42-cf36e360efce">

**Comment by maryjaf** [comment]
> The referenced attestation id is not filled in your attestation

It is a optional field, so it should be filled to the attestation be counted, 
It isn't better that this field be required ?

**Comment by divine-comedian** [comment]
> > The referenced attestation id is not filled in your attestation
> 
> It is a optional field, so it should be filled to the attestation be counted, It isn't better that this field be required ?

We don't have control over making the field mandatory since it is controlled from the EAS website where you made the attestation from. It's not related to any schema settings that we are able to manage.

We will be able to fill these things automatically for the user when they make attestations from our FE

**Comment by divine-comedian** [comment]
From our call today here is the call we can use to check if a project has previously attested to a project: 

```
query {
  projectAttestations(where: {
    attestorOrganisation: {
      attestor:{
        id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
      }
    }
    project:{
      id_in:["giveth-2880", "giveth-123"] <----- enter source + id of projects you want to check for
    }
  }) {
    id
    vouch
    attestTimestamp
    project {
      id
    }
  }
}
```

**Comment by maryjaf** [comment]
> query {
> projectAttestations(where:{
> attestorOrganisation: {
>   attestor:{
>     id_eq:"0xcd192b61a8dd586a97592555c1f5709e032f2505" 
>   }
> }
>  }) {
>   project {
>    id
>    source
>    projectId
>  }
>  attestorOrganisation {
>    attestor {
>      id
>     
>    }
>    organisation {
>      id
>      name
>    }
> 
>  }
> }
> 
>  }

If the user(0xcd192b61a8dd586a97592555c1f5709e032f2505) has 2 attestation for 2880 project id, in the response of this query only 1 record related this project id should be shown? @aminlatifi

**Comment by aminlatifi** [comment]
> > query {
> > projectAttestations(where:{
> > attestorOrganisation: {
> > attestor:{
> > id_eq:"0xcd192b61a8dd586a97592555c1f5709e032f2505"
> > }
> > }
> > }) {
> > project {
> > id
> > source
> > projectId
> > }
> > attestorOrganisation {
> > attestor {
> > id
> > }
> > organisation {
> > id
> > name
> > }
> > }
> > }
> > }
> 
> If the user(0xcd192b61a8dd586a97592555c1f5709e032f2505) has 2 attestation for 2880 project id, in the response of this query only 1 record related this project id should be shown? @aminlatifi

The tuple (user,organisation) is a uniq attestor. If the user has voted twice with single organisation, only the latest one will be there. If has attested with two orgs, both must be there.

**Comment by maryjaf** [comment]
Could you please add this address to giveth organization?
 0xcd192b61a8dd586a97592555c1f5709e032f2505
 @divine-comedian

**Comment by aminlatifi** [comment]
https://github.com/Giveth/DeVouch-BE/issues/10#issuecomment-2115233906
