### ISSUE TITLE
Fetch Giveth projects & related info

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#2]
https://mainnet.serve.giveth.io/graphql

We'll need to provide the following information for each project: 
- source of the project
- title of the project
- link to project (on source platform)
- description of the project
- project banner image (if applicable)

## Acceptance Criteria
From unified API endpoint _____ we can fetch the following details from a single Giveth project:

- [x] - source of the project
- [x] - title of the project
- [x] - 60 character shortened description of the project
- [x] - project banner image (if applicable)

From the project details endpoint ______ we can fetch the following details from a single single Giveth project:

- [x] - source of the project
- [x] - title of the project
- [ ] - link to project (on source platform)
- [x] - description of the project
- [x] - project banner image (if applicable)

**Comment by maryjaf** [comment]
https://github.com/Giveth/DeVouch-BE/assets/111529185/3cee3b52-87c6-4fe3-9623-fc8aaadd26ed

**Comment by MohammadPCh** [comment]
hmm... let's talk on fe issue :)
Thanks.

**Comment by maryjaf** [comment]
> * [x]  - by tapping on the source of project in project detail page(not project card) the user is redirected to **giveth.io** or **gitcoin.co** is this accepted our user should be redirected to the link of project in giveth or gitcoin?
> * [x]  - by tapping on the source of project "retro funding 4" the user is redirected to "https://staging.devouch.xyz/"

Thanks @MohammadPCh these two problems have been resolved

**Comment by MohammadPCh** [comment]
Do we want to redirect to project's page from there? @divine-comedian @maryjaf

**Comment by divine-comedian** [comment]
> Do we want to redirect to project's page from there? @divine-comedian @maryjaf
This is back-end focused issue, lets follow up the UI elements somewhere else 

There is a design for linking to the project source page, I've made an issue for it here - https://github.com/Giveth/DeVouch-FE/issues/100 

The source badge icon linking to the source platform page is not an MVP feature, for now it should not be a link to anything
