### ISSUE TITLE
API for attestation data of a specific user address

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#22]
An API will be needed to fetch information regarding a specific address. It will need to provide the following: 

- Projects that the given address has attested to 
- The data of each attestation made (vouch/flag, related attestor group, date, comments)
- Specific data regarding each project they attested to - Title, source, ID, slug, source link

The should be able to FILTER this data by: 
- Projects from only a specific source that they have attested to
- Only a specific attestor group that they belong to (might be one or many they belong to)
- ONLY vouches they have made 
- ONLY flags they have made
- keyword search of project title

they should be able to SORT the list with or without filter by ascending/descending of date attestation was made

**Comment by aminlatifi** [comment]
@divine-comedian All are satisfied, except for the project slug and source link. About the
- Slug: Do we need it? we can add a field to the project for it.
- Source link: I think it can be built on the frontend with `source` and `projectId`. BTW, we define a link in the project to have it. WDYT?

**Comment by divine-comedian** [comment]
@aminlatifi We'll need to find a way to link users to see the page where the project lives natively, on its source, this could be fetched from the provided source APIs and we'll need to figure that out. 

the link to the project on the DeVouch platform we can handle ourselves - I think generating the slug as you have suggested is a great idea, by `source` + `projectId` e.g. `devouch.xyz/project/giveth-2881`

**Comment by aminlatifi** [comment]
> @aminlatifi We'll need to find a way to link users to see the page where the project lives natively, on its source, this could be fetched from the provided source APIs and we'll need to figure that out.
> 
> the link to the project on the DeVouch platform we can handle ourselves - I think generating the slug as you have suggested is a great idea, by `source` + `projectId` e.g. `devouch.xyz/project/giveth-2881`

You are right.
@MohammadPCh, would you please save project slug or URL as well?
