### ISSUE TITLE
[needs project info] Retrieve attestations made by address

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#23]
For each attestation made by the given user address we need to make available the following information: 

- [x] - Title of project attested to
- [x] source platform of project (giveth, gitcoin, RPGF etc..)
- [x] - date of attestation
- [x] - name of attestor group(s) they attested as
- [x] - comments made with given attestation if applicable
- [x] - if attestation is flag or vouch
- [x] link/slug to project details page

**Comment by aminlatifi** [comment]
Sample query
```graphql
{
  projectAttestations(where: {attestorOrganisation: {attestor: {id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"}}}) {
    attestTimestamp
    comment
    vouch
    project {
      id
      title
    }
    attestorOrganisation {
      attestor {
        id
      }
      organisation {
        name
      }
    }
  }
}

```
Response
```json
{
  "data": {
    "projectAttestations": [
      {
        "attestTimestamp": "2024-05-09T17:36:36.000000Z",
        "comment": "this is awesome",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "title": null
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          },
          "organisation": {
            "name": "Giveth Verification Team"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-10T12:24:36.000000Z",
        "comment": "cool project! good luck",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "title": null
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          },
          "organisation": {
            "name": "Trace"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-12T16:26:36.000000Z",
        "comment": "Does it show up now?",
        "vouch": true,
        "project": {
          "id": "giveth-2881",
          "title": null
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          },
          "organisation": {
            "name": "Trace"
          }
        }
      }
    ]
  }
}
```

**Comment by maryjaf** [comment]
> [ ] - Title of project attested to

- [ ] 1- Title is null  @aminlatifi 

{
    "data": {
        "projectAttestations": [
            {
                "attestTimestamp": "2024-05-13T09:21:24.000000Z",
                "comment": "",
                "vouch": false,
                "project": {
                    "id": "giveth-2881",
                    "title": null,
                    "source": "giveth"
                },
                "attestorOrganisation": {
                    "attestor": {
                        "id": "0xcd192b61a8dd586a97592555c1f5709e032f2505"
                    },
                    "organisation": {
                        "name": "Trace"
                    }
                }
            },
            {
                "attestTimestamp": "2024-05-19T06:54:12.000000Z",
                "comment": "testaaaaaa",
                "vouch": true,
                "project": {
                    "id": "giveth-2880",
                    "title": null,
                    "source": "giveth"
                },
                "attestorOrganisation": {
                    "attestor": {
                        "id": "0xcd192b61a8dd586a97592555c1f5709e032f2505"
                    },
                    "organisation": {
                        "name": "Trace"
                    }
                }
            },
            {
                "attestTimestamp": "2024-05-19T07:38:48.000000Z",
                "comment": "testflagi",
                "vouch": false,
                "project": {
                    "id": "giveth-2880",
                    "title": null,
                    "source": "giveth"
                },
                "attestorOrganisation": {
                    "attestor": {
                        "id": "0xcd192b61a8dd586a97592555c1f5709e032f2505"
                    },
                    "organisation": {
                        "name": "Giveth Verification Team"
                    }
                }
            }
        ]
    }
}

**Comment by maryjaf** [comment]
> [ ] link/slug to project details page

- [ ] 2- I haven't seen above field in the response
