### ISSUE TITLE
[needs project data] Filter user attestations by one or many attestor group(s) they belong to

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#25]
we should be able to filter the data of all attestations made by a specific user to only show attestations they have made from a specific attester organization/group

## AC 
when querying https://backend.devouch.xyz/graphql we should be able to look for user attestations and filter by a specific attester group, the response should include:

- [x] does not include attestations from other attester groups
- [x] pagination works to see all attestations (skip, take, limit etc..) 
- [x] title of project 
- [x] source platform (giveth, gitcoin, rpgf)
- [x] link/slug to project details 
- [x] attester group attestation was done as
- [x] if it was a vouch
- [x] comment included in attestation (if applicable)
- [x]  date of attestations

**Comment by aminlatifi** [comment]
Sample query
```graphql
{
  projectAttestations(
    where: {
      attestorOrganisation: 
      {attestor: 
        {id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"}
        organisation:{
          name_in:["Trace", "Giveth Verification Team"]
        }
      }

    }
  ) {
    attestTimestamp
    comment
    vouch
    project {
      id
      title
    }
    attestorOrganisation {
      organisation {
        name
      }
    }
  }
}

```
Response
```json
{
  "data": {
    "projectAttestations": [
      {
        "attestTimestamp": "2024-05-09T17:36:36.000000Z",
        "comment": "this is awesome",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "title": null
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Giveth Verification Team"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-10T12:24:36.000000Z",
        "comment": "cool project! good luck",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "title": null
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Trace"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-12T16:26:36.000000Z",
        "comment": "Does it show up now?",
        "vouch": true,
        "project": {
          "id": "giveth-2881",
          "title": null
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Trace"
          }
        }
      }
    ]
  }
}
```

**Comment by divine-comedian** [comment]
This still needs project information to be included such as title

**Comment by divine-comedian** [comment]
FYI example I was also able to get it with 
```
{
  projectAttestations(limit: 10, offset: 0, where: {attestorOrganisation: {attestor: {id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"}, AND: {id_eq: "0xbc4670cf362077fe4ce70ce3097ceac6af2312e6c808dd6b3f3f58912b1cc32c", OR: {id_eq: "0x75ab7d38d782548ed161f95d1674ca0e7a7880cb21c32d8372333486e3009d07"}}}}) {
    attestTimestamp
    comment
    vouch
    project {
      source
      title
      slug
    }
    attestorOrganisation {
      id
      attestor {
        id
      }
      organisation {
        name
      }
    }
  }
}

```

**Comment by aminlatifi** [comment]
> FYI example I was also able to get it with
> 
> ```graphql
> {
>   projectAttestations(limit: 10, offset: 0, where: {attestorOrganisation: {attestor: {id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"}, AND: {id_eq: "0xbc4670cf362077fe4ce70ce3097ceac6af2312e6c808dd6b3f3f58912b1cc32c", OR: {id_eq: "0x75ab7d38d782548ed161f95d1674ca0e7a7880cb21c32d8372333486e3009d07"}}}}) {
>     attestTimestamp
>     comment
>     vouch
>     project {
>       source
>       title
>       slug
>     }
>     attestorOrganisation {
>       id
>       attestor {
>         id
>       }
>       organisation {
>         name
>       }
>     }
>   }
> }
> ```

I am not sure it's correct syntax
```
AND: {id_eq: "0xbc4670cf362077fe4ce70ce3097ceac6af2312e6c808dd6b3f3f58912b1cc32c", OR: {id_eq: "0x75ab7d38d782548ed161f95d1674ca0e7a7880cb21c32d8372333486e3009d07"}}
```
I would use this
```
id_in: ["0xbc4670cf362077fe4ce70ce3097ceac6af2312e6c808dd6b3f3f58912b1cc32c", "0x75ab7d38d782548ed161f95d1674ca0e7a7880cb21c32d8372333486e3009d07"]
```
