### ISSUE TITLE
[needs project data] Filter by vouches/flags made by user address

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#26]
Filter the response to ONLY show Vouches made by address 

OR 

Filter the response to ONLY show Flags made by address 

https://backend.devouch.xyz/graphql

## AC
we should be able to query the endpoint above, for a specific user address, filtered by only vouches or flags, the response should be able to include:

**For Vouches**
- [x] all vouches made by a user 
- [x] does not include flags made by user
- [x] pagination works to see all vouches (skip, take, limit etc..) 
- [x] title of project 
- [x] source platform (giveth, gitcoin, rpgf)
- [x] link/slug to project details 
- [x] attester group attestation was done as
- [x] if it was a vouch
- [x] comment included in attestation (if applicable)
- [x]  date of attestations 

**For Flags**
- [x] all flags made by a user 
- [x]  does not include vouches made by user
- [x] pagination works to see all vouches (skip, take, limit etc..) 
- [x] title of project 
- [x] source platform (giveth, gitcoin, rpgf)
- [x] link/slug to project details 
- [x] attester group attestation was done as
- [x] if it was a flag
- [x] comment included in attestation (if applicable)
- [x] date of attestations

**Comment by divine-comedian** [comment]
@aminlatifi are there any limitations to the amount of data it returns in the response? Did we consider imposing any limits in the response and use pagination, assuming a user or any entity really could have 100s of objects in its response.

**Comment by aminlatifi** [comment]
> Referen

There is built-in pagination support with `limit` and `skip` parameters. Also, subsquid has a more advanced alternative with cursor support.

**Comment by maryjaf** [comment]
I had tested this issue and moved it to done.
