### ISSUE TITLE
[needs project info] Filter user attestations by keyword search of project title

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#27]
When querying for attestations made by a specific user, we should be able to search by title of a project name and get some results of the required project info and attestation data related to it.

## AC

- [x] partial spelling of project title returns expected results
- [x] complete/exact spelling of project title returns correct results

Attestation info contains:
- [x] - Title of project attested to
- [x] source platform of project (giveth, gitcoin, RPGF etc..)
- [x] - date of attestation
- [x] - name of attestor group(s) they attested as
- [x] - comments made with given attestation if applicable
- [x] - if attestation is flag or vouch
- [x] link/slug to project details page

**Comment by aminlatifi** [comment]
We don't have any project with a filled `title` field, so I demonstrate it with the `source` field. 
It's a sample query that search terms are split and used in an OR conjunction
```graphql
{
  projectAttestations(where: {attestorOrganisation: {attestor: {id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"}}, project: {OR: [{source_containsInsensitive: "giv"}, {source_containsInsensitive: "git"}]}}) {
    attestTimestamp
    comment
    vouch
    project {
      source
    }
    attestorOrganisation {
      organisation {
        name
      }
    }
  }
}
```
Sample json response
```json
{
  "data": {
    "projectAttestations": [
      {
        "attestTimestamp": "2024-05-09T17:36:36.000000Z",
        "comment": "this is awesome",
        "vouch": true,
        "project": {
          "source": "giveth"
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Giveth Verification Team"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-10T12:24:36.000000Z",
        "comment": "cool project! good luck",
        "vouch": true,
        "project": {
          "source": "giveth"
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Trace"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-12T16:26:36.000000Z",
        "comment": "Does it show up now?",
        "vouch": true,
        "project": {
          "source": "giveth"
        },
        "attestorOrganisation": {
          "organisation": {
            "name": "Trace"
          }
        }
      }
    ]
  }
}
```

**Comment by divine-comedian** [comment]
We'll need the project info to call this one done. moving back to in progress.
