### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/DeVouch-BE#29]
The CI/CD solution must be able to deploy a subsquid project automatically and set configurations (e.g. RPC node) in .env file

**Comment by aminlatifi** [comment]
@mhmdksh How is the progress on this? It would be greate if have it ready for tests.
Also, I forgot a key requirements! On every new deployment, the app must see a fresh db to run again migration and there must be no leftover from before.
The subsquid command line does it with `sqd down` by deleting postgres containers.

**Comment by divine-comedian** [comment]
@mhmdksh is this finished, can we close this one?

**Comment by aminlatifi** [comment]
@mhmdksh Let's create on deployment for production to index optimism mainnet network. It should deploy on pushing to the `main` branch with these changes to config:
SQUID_NETWORK=optimism-mainnet
RPC_ENDPOINT=<archive support optimism mainnet rpc url>

**Comment by mhmdksh** [comment]
> @mhmdksh is this finished, can we close this one?

This was done to ETH Sepolia, but not with the current OP Mainnet Deployment

**Comment by mhmdksh** [comment]
> @mhmdksh Let's create on deployment for production to index optimism mainnet network. It should deploy on pushing to the `main` branch with these changes to config: SQUID_NETWORK=optimism-mainnet RPC_ENDPOINT=

For sure, I'll work on that and update you here :)

**Comment by mhmdksh** [comment]
@divine-comedian This has been done and implemented. It can be closed now
