### ISSUE TITLE
Sort count of vouches for all tracked attestor groups for a project by highest/lowest

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#31]
From the query response of all projects for the list view - we will need to be able to know the count from each registered/tracked attester groups that have VOUCHED a project and show the count in order from group that has made the MOST flags down the group that has made the lowest (descending order)

It will be used on this card component to give you a visual example: 
![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/4dee312b-16ec-418d-88cd-8fe177f0ab56)

## AC 
in the query response should fulfill the following requirements:

- [ ] vouches are sorted in correct order from highest to lowest
- [ ] count is correct number 
- [ ] title of attestor organization is included in response

**Comment by aminlatifi** [comment]
It's like #34
