### ISSUE TITLE
[needs project info] Filter unified list by project source

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#32]
When getting the unified list of projects we should be able to filter for only projects that are from a particular source such as Giveth, Gitcoin or RPGF. 

The response should only show projects from the filtered platform, along with any other applicable filtering or sorting applied.

## AC
 
- [x] can filter list for only projects from Giveth
- [x] can filter list for only projects from Gitcoin
- [x] can filter list for only projects from RPGF
- [x] does not return projects from platform not specified in filter query

each project returned in the response has the following data: 

- [x] the titles of the project
- [x] the source platform
- [x] the short description of the project
- [x] count of flags AND vouches made my all attestor groups for each project listed in response
- [x] comment included in attestation
- [x] banner image

**Comment by aminlatifi** [comment]
sample query
```graphql
{
  projects(where:{
    source_in:["giveth"],
  },
    orderBy:totalFlags_ASC
  ) {
    id
    totalVouches
    totalFlags
    totalAttests
  }
}
```
response
```json
{
  "data": {
    "projects": [
      {
        "id": "giveth-2880",
        "totalVouches": 3,
        "totalFlags": 0,
        "totalAttests": 3
      },
      {
        "id": "giveth-2881",
        "totalVouches": 1,
        "totalFlags": 0,
        "totalAttests": 1
      },
      {
        "id": "giveth-123",
        "totalVouches": 1,
        "totalFlags": 2,
        "totalAttests": 3
      }
    ]
  }
}
```

**Comment by maryjaf** [comment]
> * [ ]  can filter list for only projects from Gitcoin
> * [ ]  can filter list for only projects from RPGF

> 
> each project returned in the response has the following data:
> 
> * [ ]  the titles of the project
> * [ ]  the short description of the project
> * [ ]  banner image

- [ ] 
These ACs aren't testable now.
