### ISSUE TITLE
[needs project info] Filter unified list based on keyword search of project title

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#33]
There will be a keyword search function available, we should be able to take in a keyword search in our query and return a sorted list of results that are closes to the keyword match. 

This should also be able to handle any filters that have been applied in the query as well such as attester group or source platform

## AC
 
- [x] can handle filtered by source platform
- [x] can handle filtering by attester group
- [x] returns expected results using search of partial project title
- [x] returns expected results using search of complete project title

each project returned in the response has the following data: 

- [x] the titles of the project
- [x] the source platform
- [x] the short description of the project
- [x] count of flags AND vouches made by all attestor groups for each project listed in response
- [x] banner image

**Comment by aminlatifi** [comment]
@divine-comedian It would be something like #21 
If you need sorting based on similarity to search term, it's not implemented in the backend and subsquid doesn't have such support. As an easy option, we can fetch projects all in the frontend and order by similarity there.

**Comment by divine-comedian** [comment]
> @divine-comedian It would be something like #21 If you need sorting based on similarity to search term, it's not implemented in the backend and subsquid doesn't have such support. As an easy option, we can fetch projects all in the frontend and order by similarity there.

We'll need to handle this somehow, assuming we have thousands of projects we want the best way to deal with it. Currently on Giveth do we handle this via the FE?

**Comment by aminlatifi** [comment]
I mean #27 issue, sorry.
There is a `<field>__containsInsensitive` option for querying string-type fields that allows us to run queries [LIKE](https://www.w3schools.com/sql/sql_like.asp) queries.
It's worth mentioning that we haven't implemented any custom resolver/API ourselves and the GraphQL API we use now are generated based on entities designed on the Subsquid. Likewise, the `<field>__containsInsensitive` option is enabled on any string-type field and if it works as we expect on a field with this type, we can expect the same behaviour on any other string type field like `title`, `description`, etc.

**Comment by divine-comedian** [comment]
JFYI this is the query I used - looking good! 

```
{
  projects(where: {title_containsInsensitive: "women"}) {
    totalFlags
    totalVouches
    title
    source
    description
    slug
    attestedOrganisations {
      id
      count
      vouch
  
    }
  }
}
```
