### ISSUE TITLE
[needs project info] sort user attestations alphabetically by project title

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#35]
When fetching attestations done by a user address we should be able to sort the responses according to the alphabetical order by project title in both ascending and descending order. 

## AC 

- [x] can query attestation data for a single user
- [x] does not return data for other users not specified
- [x] can sort by project title alphabetically in ascending order
- [x] can sort by project title alphabetically in descending order

attestation data contains:

- [x] if flag or vouch
- [x] name of attester organization the attestation was associated with
- [x] comments included in attestation (if any)
- [x] date attestation was made
- [x] title of project 
- [x] slug/link to project
- [x] source platform of project

**Comment by aminlatifi** [comment]
We haven't filled in the project title yet, let's demonstrate with the project ID.
Sample query
```graphql
{
  projectAttestations(
    where:{
      attestorOrganisation: {
        attestor: {
          id_eq: "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
        }
      }
    },
    orderBy: project_id_ASC
  ) {
    attestTimestamp
    vouch
    project {
      id
      source
    }
    attestorOrganisation {
      attestor {
        id
      }
    }
  }
}

```
Sample response
```json
{
  "data": {
    "projectAttestations": [
      {
        "attestTimestamp": "2024-05-09T17:36:36.000000Z",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "source": "giveth"
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-10T12:24:36.000000Z",
        "vouch": true,
        "project": {
          "id": "giveth-2880",
          "source": "giveth"
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          }
        }
      },
      {
        "attestTimestamp": "2024-05-12T16:26:36.000000Z",
        "vouch": true,
        "project": {
          "id": "giveth-2881",
          "source": "giveth"
        },
        "attestorOrganisation": {
          "attestor": {
            "id": "0x826976d7c600d45fb8287ca1d7c76fc8eb732030"
          }
        }
      }
    ]
  }
}
```

**Comment by divine-comedian** [comment]
We'll need the project information to be included in this in order to call it done!

**Comment by maryjaf** [comment]
"title","description" and "slug" have been added.
