### ISSUE TITLE
Acquire website domain

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#36]

**Comment by mhmdksh** [comment]
@divine-comedian For the backend right?? What would it be?? Should it be a subdomain under giveth.io??

**Comment by divine-comedian** [comment]
@geleeroyale acquired the domain on Wednesday 

DeVouch.xyz 😎

**Comment by mhmdksh** [comment]
> @geleeroyale acquired the domain on Wednesday
> 
> DeVouch.xyz 😎

Oh, sweet 😎
