### ISSUE TITLE
Provision Sepolia archive JRPC Node

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/DeVouch-BE#38]
The attestation service runs on the Sepolia network. Our indexer (Subsquid) needs an archive node of Sepolia chain (11155111) for staging env.
We can use personal alchemy nodes for development purpose, but it's safer to have a separate one on the server.

**Comment by divine-comedian** [comment]
@mhmdksh - Did this get done?

**Comment by divine-comedian** [comment]
@mhmdksh can you update this issue? can we close it?

**Comment by mhmdksh** [comment]
@divine-comedian Yes this has been done we now have two environments. One for staging and one for production.

Currently eth sepolia is configured with an rpc on staging

We can close this now
