### ISSUE TITLE
Fetch Gitcoin projects & related info

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#4]
https://grants-stack-indexer-v2.gitcoin.co/graphiql
We'll need to provide the following information for each project:

- source of the project
- title of the project
- link to project (on source platform)
- description of the project
- project banner image (if applicable)

## Acceptance Criteria
From unified API endpoint _____ we can fetch the following details from a single Gitcoin grant project:

- [ ] - source of the project
- [ ] - title of the project
- [ ] - 60 character shortened description of the project
- [ ] - project banner image (if applicable)

From the project details endpoint ______ we can fetch the following details from a single Gitcoin grant project:

- [ ] - source of the project
- [ ] - title of the project
- [ ] - link to project (on source platform)
- [ ] - description of the project
- [ ] - project banner image (if applicable)

**Comment by divine-comedian** [comment]
@aminlatifi - we should check how we choose to alias gitcoin grants - is it by a eth address or their profileID as provided by allo protocol?

**Comment by aminlatifi** [comment]
@divine-comedian We defined `ProjectId` field as string to have freedom in the value to save.

**Comment by aminlatifi** [comment]
@MohammadPCh I see no value in the slug or image field of gitcoin projects. Can we generate project URL or image?

**Comment by divine-comedian** [comment]
I found the image as an ipfs hash in the response, tested it and it works as a valid image.  

![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/cfc5d917-db0b-4414-b759-adebf9e99425)

I asked Kurt if there was a way to get the project URL from the API, I can't see any relevant information in the API response but maybe you guys have had better luck.

**Comment by maryjaf** [comment]
All acceptance criteria are shown correctly 
 - source of the project
 - title of the project
 - 60 character shortened description of the project
 - project banner image (if applicable)
 
**but by tapping on "from gitcoin" label, the user is redirected to https://www.gitcoin.co/ not project address on gitcoin** 
@MohammadPCh 

![image](https://github.com/Giveth/DeVouch-BE/assets/111529185/19941777-1916-46ca-9a3f-f0b73cf27585)

**Comment by 0xKurt** [comment]
> https://grants-stack-indexer-v2.gitcoin.co/graphiql OR https://indexer-staging.fly.dev/graphiql
> 

don't use `https://indexer-staging.fly.dev/graphiql` anymore
