### ISSUE TITLE
Default Sort response by count of attestation on projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#48]
The default sorting given by the unified API response of the projects should be projects that have the highest count of attestations (vouch AND Flags together) from all tracked attester groups. 

If a filter has been applied to look only for a certain attester group then the default sorting should filter by this as well. Similarly if we filter for a specific platform.

**Comment by divine-comedian** [comment]
@aminlatifi  - Did we already figure this one out?

**Comment by aminlatifi** [comment]
We can add define sort condition in queries like this
```graphql
query {
  projects(orderBy:totalAttests_DESC, where: {
    attestedOrganisations_some:{
      organisation: {
        name_eq: "Trace"
      }
    }
  }) {
    title
    totalAttests
    totalVouches
    totalFlags
    attestedOrganisations {
      organisation {
        name
      }
      vouch
      count
    }
  }
}
```

**Comment by divine-comedian** [comment]
thanks! tested and response is as expected
