### ISSUE TITLE
Periodically fetching project information from source APIs

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#52]
We'll need to determine how often we fetch the project information from API  

I believe we should do this at least once a day - this will be a devOps issue in the configuration

@aminlatifi could you provide more details on this? Once we setup the back-end logic for retrieving project information there needs to be some sort of cronJob that call its periodically and updates our DB?

**Comment by aminlatifi** [comment]
> We'll need to determine how often we fetch the project information from API
> 
> I believe we should do this at least once a day - this will be a devOps issue in the configuration
> 
> @aminlatifi could you provide more details on this? Once we setup the back-end logic for retrieving project information there needs to be some sort of cronJob that call its periodically and updates our DB?

We are implementing this routine, define a cronjob express in the configuration to run the project import task accordingly. 
Also, we are going to create a github action which allow us to trigger the process manually in case we want.
