### ISSUE TITLE
deploy subsquid service on Optimism from Sepolia

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#56]
can change EAS contract, schema contract etc. are all in the environment variables. 

here is our attestation schema on optimism
https://optimism.easscan.org/schema/view/0x97b0c9911936fad57e77857fac6eef6771f8d0bf025be9549214e32bf9e2415a

EAS contract:
https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000021

**Comment by mhmdksh** [comment]
@divine-comedian 
This has been deployed. Here are the details:

1. It is up and running, and in a deployable state
2. The Logs for the OP Mainnet backend and directly reflected in our logging system at this link: https://logs.giveth.io/d/d60d0940-f316-4936-bf0d-a658bc3ecd67/devouch-backend-optimism-mainnet?orgId=1
3. The configuration to the Devouch backend can be modified by our devs in our secret manager at this directory: https://vault.giveth.io/ui/vault/secrets/devouch-kv/show/prod/config
4. The GraphQL can be accessed through the following link: https://optimism.backend.devouch.xyz/graphql

**Comment by divine-comedian** [comment]
@aminlatifi can you follow up here and let me know if you approve this issue, then we can call it done.

**Comment by aminlatifi** [comment]
> @aminlatifi can you follow up here and let me know if you approve this issue, are we missing anything important? Otherwise then we can call it done.

It seems good.
