### ISSUE TITLE
Create Schema for Flag/Vouching Attestations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#6]
This schema will need to contain fields for the following information

- if it's a flag or a vouch
- the source and id of the project
- attestor group they are attesting as (possibly multiple or none)
- comment related to their attestation

## Acceptance Criteria
Can successfully create on-chain attestation using generated schema on EAS website with the following fields: 
- [ ] flag/vouch boolean (true for vouch, false for flag)
- [ ] source of project (giveth, gitcoin, optimism) as string
- [ ] id of project (number)
- [ ] reference field to use UID of attestation issued to authorized attestor that identifies them
- [ ] string containing a comment

link to schema:
https://sepolia.easscan.org/schema/view/0x97b0c9911936fad57e77857fac6eef6771f8d0bf025be9549214e32bf9e2415a

**Comment by divine-comedian** [comment]
@aminlatifi  - What do you think of the format we need for the schema? 

- how should we format the array containing the attestor groups they are using in the attestation? 
- should we add comments as raw strings or as IPFS hashes containing the comment? The comments will be limited to 256 characters. (like a tweet)

**Comment by aminlatifi** [comment]
- I think it's better to keep the schema simple and design it for a single attestation. Hopefully, the EAS contract designers have seen such requirements and added a `multiAsset` method that allows submitting multiple attestations in a single transaction. 
So, we can implement our FE to get multiple attestations data from users and submit all in a single transaction.
![Image](https://github.com/Giveth/DeVouch-BE/assets/5684607/9b23963b-132b-4fdc-8f6f-f48ea643a70a)

- The schema has a field of type String with arbitrary length. I think we can go ahead using that so far. In the future, if we see it's not enough we can change the FE only and submit an IPFS link in this field.
![Image](https://github.com/Giveth/DeVouch-BE/assets/5684607/77ff7b7f-c5ad-4e04-aa0f-8519e5614dc8)

**Comment by aminlatifi** [comment]
@divine-comedian I defined `projectId` as string to have a flexibility in defining projects. We need it since in Giveth `projectId` is of type number but in gitcoin it's like an ethereum address.

**Comment by aminlatifi** [comment]
@divine-comedian I defined the schema here, made the attestorGroup as array as you wished so far
https://sepolia.easscan.org/schema/view/0x9e55855a361f8ff089592b238c6341c880a9228521d87be3fd8fa8922d88c484

**Comment by divine-comedian** [comment]
Based on the changes in #40 we should consider making a new schema that doesn't allow attestations made with multiple attestor groups 

- if it's a flag or a vouch
- the source and id of the project
- attestor group they are attesting as, only accepts one (by schema ID(?))
- comment related to their attestation

**Comment by aminlatifi** [comment]
@divine-comedian Attestation has a field named reference attestation. I think using this field to refer to the authorization attestation would be tactful. If you agree with me we can remove the `attestorGroup` from the project verification attestation and use this to refer to the attention authorized the very user is attesting to the project.


![Image](https://github.com/Giveth/DeVouch-BE/assets/5684607/5138b815-5402-4233-95d7-33b6380b9715)

**Comment by divine-comedian** [comment]
Please provide a link to the schema once you have finalized it @aminlatifi

**Comment by aminlatifi** [comment]
@divine-comedian It's the new version
https://sepolia.easscan.org/schema/view/0x97b0c9911936fad57e77857fac6eef6771f8d0bf025be9549214e32bf9e2415a

**Comment by divine-comedian** [comment]
Added to Optimism 
https://optimism.easscan.org/schema/view/0x97b0c9911936fad57e77857fac6eef6771f8d0bf025be9549214e32bf9e2415a

**Comment by maryjaf** [comment]
Could you please give me an access to Giveth/Devouch ?
I couldn't update the status of this issue

**Comment by aminlatifi** [comment]
> Could you please give me an access to Giveth/Devouch ? I couldn't update the status of this issue

Done
