### ISSUE TITLE
Convert project description responses to HTML

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#69]
> I've fixed the length, but to show the styled version, we need to convert it to the html on BE, I'll do it after the MVP.

_Originally posted by @MohammadPCh in https://github.com/Giveth/DeVouch-FE/issues/65#issuecomment-2151937354_

---

In order to properly handle markdown formatted responses received in the project description we'll need to convert it to HTML in the back-end. This will allow us to show properly formatted project descriptions  

e.g. of the visual problems we hope to solve:
![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/b768b80d-4fc7-4a00-bc8b-9db9c65dd67e)
 
![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/55cd5e32-0cfe-4502-a010-e95cfad44a48)

**Comment by divine-comedian** [comment]
for retrofunding projects we are not considering the line breaks provided in the response to format the descriptions on the devouch UI 

![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/5fdd704b-c37b-4211-b526-de4e584ae206)

also some projects have markdown formatting for headers we should consider, either show the headers or remove the markdown syntax
![image](https://github.com/Giveth/DeVouch-BE/assets/67759413/0977d276-496d-4bfc-acde-5d2a8fc3b2a1)



```graphql
query MyQuery {
  projectById(id: "rf4-0x897d6172efca2d24a6b14f235db5127f7d747d923287ede38d776126bf02cbfe") {
    description
    id
  }
}
```

**Comment by MohammadPCh** [comment]
@maryjaf READY TO TEST

**Comment by maryjaf** [comment]
> also some projects have markdown formatting for headers we should consider, either show the headers or remove the markdown syntax

It seems it hasn't been fixed. @MohammadPCh 
https://staging.devouch.xyz/project/rf4/0x2a3435d9ce08d7c960819e627601ce3907ff0fea5ae7e7d111a869d815a2eb89

**Comment by MohammadPCh** [comment]
@maryjaf It's looking fine for me:
<img width="1486" alt="Screenshot 2024-06-12 at 9 44 01 PM" src="https://github.com/Giveth/DeVouch-BE/assets/17097576/5c6345ce-a16f-4682-980f-7c4acc70f3c4">
Maybe it was in the build queue when you tested it.
can you check it again?

**Comment by divine-comedian** [comment]
> @maryjaf It's looking fine for me: <img alt="Screenshot 2024-06-12 at 9 44 01 PM" width="1486" src="https://private-user-images.githubusercontent.com/17097576/339084524-5c6345ce-a16f-4682-980f-7c4acc70f3c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTc0NzAsIm5iZiI6MTcxODIxNzE3MCwicGF0aCI6Ii8xNzA5NzU3Ni8zMzkwODQ1MjQtNWM2MzQ1Y2UtYTE2Zi00NjgyLTk4MGYtN2M0YWNjNzBmM2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE4MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZDgwMjdhMzVkYTRmNzI4YmE5Y2FhOTA2OWIyMDNjOTFmNWUwY2JjYjE5YWYwYzVmNjczOGQ3YTRjMWIwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFkd4_Pdo2_awugh232EeK32iIFyjz2PXHiIO283ELo"> Maybe it was in the build queue when you tested it. can you check it again?

Is it possible to also handle the markdown formatting?

**Comment by aminlatifi** [comment]
> > @maryjaf It's looking fine for me: <img alt="Screenshot 2024-06-12 at 9 44 01 PM" width="1486" src="https://private-user-images.githubusercontent.com/17097576/339084524-5c6345ce-a16f-4682-980f-7c4acc70f3c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTc0NzAsIm5iZiI6MTcxODIxNzE3MCwicGF0aCI6Ii8xNzA5NzU3Ni8zMzkwODQ1MjQtNWM2MzQ1Y2UtYTE2Zi00NjgyLTk4MGYtN2M0YWNjNzBmM2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE4MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZDgwMjdhMzVkYTRmNzI4YmE5Y2FhOTA2OWIyMDNjOTFmNWUwY2JjYjE5YWYwYzVmNjczOGQ3YTRjMWIwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFkd4_Pdo2_awugh232EeK32iIFyjz2PXHiIO283ELo"> Maybe it was in the build queue when you tested it. can you check it again?
> 
> Is it possible to also handle the markdown formatting?

We have handled md formatting, for gitcoin. But we are not sure Retro Funding 4 projects' description are text or md?

**Comment by maryjaf** [comment]
> Maybe it was in the build queue when you tested it.
> can you check it again?

I meant these headers, Is this the expected result ? @MohammadPCh 
 
## Giveth supports P2P donations on Optimism and Base.

## How it works

**Comment by maryjaf** [comment]
> It's looking fine for me:
> <img alt="Screenshot 2024-06-12 at 9 44 01 PM" width="1486" src="https://private-user-images.githubusercontent.com/17097576/339084524-5c6345ce-a16f-4682-980f-7c4acc70f3c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjM3NzksIm5iZiI6MTcxODI2MzQ3OSwicGF0aCI6Ii8xNzA5NzU3Ni8zMzkwODQ1MjQtNWM2MzQ1Y2UtYTE2Zi00NjgyLTk4MGYtN2M0YWNjNzBmM2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA3MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYjViZmUyMWI0NTYxYTc4MmI0MGI3ZmUzMmI5MWNiOGUzZWIxN2Q4MDQ1YzZhY2MzNWUzZDY5ODBhMWJlZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FNGufqRSw1tWlo2q5ddY8Kqj_aTZIDzVgs003BbVkyM">
> Maybe it was in the build queue when you tested it.
> can you check it again?

I meant these headers, Is this the expected result ? @MohammadPCh 

   ##  Giveth supports P2P donations on Optimism and Base.

   ##  How it works

**Comment by divine-comedian** [comment]
Good question! 

I can only find the Giveth project that makes use of markdown formatting - I'm not sure we can find other applications that also use markdown, at any rate, if we can at least handle header types and space breaks I think it will satisfy the requirements for now.
