### ISSUE TITLE
Develop Subquid Service

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#7]
We'll need to develop a [subquid service ](https://subsquid.io/)to serve as the main back-end service, providing information to not only the DeVouch front-end but also external organizations who wish to integrate our attestations data layer. 

Technical Design of this service has been started by @aminlatifi  in https://www.notion.so/giveth/Project-Verification-Attestation-Support-Design-a991597acd0e4220b23131fa434e2339

### A note on Attestor Groups
These are groups of web3 users who belong to an organization or team that have some sort of notable reputation. In DeVouch we identify Attestor Groups by two parameters: 
- Holds an attestation from a specific schemaID
- Attestation they hold was minted from a specific address (issuing authority)

## This service should be queryable via graphQL and allow for the following operations: 

**Index on-chain attestation events as they occur**
-  Only for users who use our defined attestation schema #6 
- Parse & make queryable all details included in our defined schema #6 

**Query project related information**
- Only Vouches made to this project by a given attestor group (using the two necessary parameters defined above)
- Only Flags made to this project by a given attestor group (using the two necessary parameters defined above)
- All attestations made to this project, vouch or flag, by a given attestor group
- Count of flags/vouches made to this project by given attestor group
- Addresses that have vouched/flagged this project & what attestor groups they attested from

**Query user related information**
- Projects that have been vouched for by the given user address
- Projects that have been flagged for by the given user address
- All attestations, vouch or flag, made to projects by the given user address
- If an address belongs to a given attestor group (?)

**Comment by aminlatifi** [comment]
@divine-comedian 
- Can you define vouch and flag? it seems they are different.
- I think we must scope out "Project source (Gitcoin, Giveth, Optimism)". This association of a project with an organization is off-chain. As I see it, the `Project ID` is the only field we can join on-chain attestations to projects defined in Giveth (off-chain process). 
- Technically, an account can be introduced (attested to) by multiple organizations. So, if a user is a member of more than a single attestor group, I assume they can vouch per each organisation and all those vouches will be taken into account.
