### ISSUE TITLE
Unified API for retrieving projects from many sources

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#8]
We will need to provide a unified list of projects to the front-end. Projects will come from three different sources but more could be added in the future. 

The three sources in order of importance for MVP are: 

1. Agora Optimism API (pre-alpha phase) - https://vote.optimism.io/api_v1
2. Giveth - https://mainnet.serve.giveth.io/graphql
3. Gitcoin - https://grants-stack-indexer-v2.gitcoin.co/graphiql OR https://indexer-staging.fly.dev/graphiql

We'll need to provide the following information for each project: 
- source of the project
- title of the project
- preview description of the project first 60 characters
- project banner image (if applicable)

If an address is provided (user is connected to website) we will need to know for each project if the user has previously vouched/flagged a project in the list, which should be queried from #7 

Including this we will also need information from #7 to know in the unified list of projects some certain information about each project.

From each project we will need to get the list of pre-defined attester groups in #9 and query for each project for each attestor group:
- How many vouches this project has received from unique addresses
- How many unique flags this project has received from unique addresses

The unified list should be able to be FILTERED to show only projects that have been vouched for by a single attestor group, either pre-defined from #9  or a custom user-defined attestor group (by schemaID & issuing authority address). This list can be SORTED by ascending or descending order based on the count of vouches OR flags it has received from the given attestor group. By default the unified list is SORTED by highest -> lowest count of vouches made by all tracked attestor groups

Lastly, the unified list should be able to be filtered additionally with a keyword search of title provided by the user.

**Comment by divine-comedian** [comment]
@divine-comedian  - need to define sorting information for this.

**Comment by aminlatifi** [comment]
@divine-comedian can you double check optimism and coingecko project source APIs? they seems to be not ready.

**Comment by divine-comedian** [comment]
> @divine-comedian can you double check optimism and coingecko project source APIs? they seems to be not ready.

The Optimism ones are not ready, we are not using coingecko...

**Comment by aminlatifi** [comment]
> > @divine-comedian can you double check optimism and coingecko project source APIs? they seems to be not ready.
> 
> The Optimism ones are in alpha phase they just released this yesterday - https://vote.optimism.io/api_v1
> 
> We are not using coingecko...

@divine-comedian Sorry I mean gitcoin

**Comment by divine-comedian** [comment]
@aminlatifi  try this one for Gitcoin - https://indexer-staging.fly.dev/graphiql
