### ISSUE TITLE
Modifiable list of pre-defined attestor groups

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#9]
pre-defined attestor groups will be arbitrarily added by DeVouch at launch and expanded as more external teams wish to integrate with DeVouch. 

An attestor group is defined by 3 fields: 
- schemaID
- issuing authority (address that has to have issued the attestation)
- name of attestor group

These attestor groups are used by #8 and other services to pass to the FE, showing vouches/flag details and counts.

This list should be structured in a way that external teams can make PRs requesting to update or add new attestor groups.

**Comment by aminlatifi** [comment]
@divine-comedian You did create an organisation, are you happy with the script?

**Comment by divine-comedian** [comment]
Yeah! I think it works great. Is there anything else left on this issue then?

**Comment by divine-comedian** [comment]
@aminlatifi 

When I was playing around with this I noticed that if there is more than one pending PR for adding an organization when the first PR merges and second PR after that will have a merge conflict because the `add-organisation.js` file has been changed. 

Is there a way to prevent this from happening? what about using the .gitignore file or something similar? 

I also noticed in the folder system we keep production and staging migrations in the same folder, do you recommend separating them?

**Comment by aminlatifi** [comment]
> @aminlatifi
> 
> When I was playing around with this I noticed that if there is more than one pending PR for adding an organization when the first PR merges and second PR after that will have a merge conflict because the `add-organisation.js` file has been changed as a result of the first PR being merged.
> 
> Is there a way to prevent this from happening? what about using the .gitignore file or something similar?
> 
> I also noticed in the folder system we keep production and staging migrations in the same folder, do you recommend separating them?

Done by https://github.com/Giveth/DeVouch-BE/pull/72

**Comment by maryjaf** [comment]
Should I do some test about this? @divine-comedian
