### ISSUE TITLE
update BE to look for two devouch schemas instead of one

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/DeVouch-BE#96]
in order to put in place the resolver contract we would need to setup the new schema to be indexed by the subsquid

**Comment by divine-comedian** [comment]
Here is the new schema to be used for staging that has been setup to use our new custom resolver - https://sepolia.easscan.org/schema/view/0x421da38e6ff5eb5d0402a4e9be70e70f961bce228e8a20d1eca19634556247fd

**Comment by divine-comedian** [comment]
@aminlatifi @MohammadPCh - how do we get this other schema to be added to the vault?

**Comment by aminlatifi** [comment]
> @aminlatifi @MohammadPCh - how do we get this other schema to be added to the vault?

Just in the ENV, set PROJECT_VERIFY_ATTESTATION_SCHEMA value to comma separated list of schemas
